<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <RootNamespace>Marain.Tenancy.PerformanceTests</RootNamespace>
    <AssemblyName>Marain.Tenancy.PerformanceTests</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <!-- StyleCop configuration -->
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
    <NoWarn>$(NoWarn);SA1600;SA1601;SA1602;SA1633</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.13.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="NSubstitute" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Marain.Tenancy.Api\Marain.Tenancy.Api.csproj" />
    <ProjectReference Include="..\Marain.Tenancy.Cli\Marain.Tenancy.Cli.csproj" />
    <ProjectReference Include="..\Marain.Tenancy.Client\Marain.Tenancy.Client.csproj" />
    <ProjectReference Include="..\Marain.Tenancy.ClientTenantProvider\Marain.Tenancy.ClientTenantProvider.csproj" />
    <ProjectReference Include="..\Marain.Tenancy.Storage.Azure.BlobStorage\Marain.Tenancy.Storage.Azure.BlobStorage.csproj" />
    <ProjectReference Include="..\Marain.Tenancy.Shared\Marain.Tenancy.Shared.csproj" />
  </ItemGroup>

</Project>