// <auto-generated/>
#pragma warning disable CS0618
using Marain.Tenancy.Client.Item.Marain.Tenant;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marain.Tenancy.Client.Item.Marain
{
    /// <summary>
    /// Builds and executes requests for operations under \{tenantId}\marain
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MarainRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The tenant property</summary>
        public global::Marain.Tenancy.Client.Item.Marain.Tenant.TenantRequestBuilder Tenant
        {
            get => new global::Marain.Tenancy.Client.Item.Marain.Tenant.TenantRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Item.Marain.MarainRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MarainRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}/marain", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Item.Marain.MarainRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MarainRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}/marain", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
