// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChildTenantsResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The continuationToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContinuationToken { get; set; }
#nullable restore
#else
        public string ContinuationToken { get; set; }
#endif
        /// <summary>The _links property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Models.ChildTenantLinksResponse? Links { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Models.ChildTenantLinksResponse Links { get; set; }
#endif
        /// <summary>The maxItems property</summary>
        public int? MaxItems { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.ChildTenantsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marain.Tenancy.Client.Models.ChildTenantsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Marain.Tenancy.Client.Models.ChildTenantsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "continuationToken", n => { ContinuationToken = n.GetStringValue(); } },
                { "_links", n => { Links = n.GetObjectValue<global::Marain.Tenancy.Client.Models.ChildTenantLinksResponse>(global::Marain.Tenancy.Client.Models.ChildTenantLinksResponse.CreateFromDiscriminatorValue); } },
                { "maxItems", n => { MaxItems = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("continuationToken", ContinuationToken);
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Models.ChildTenantLinksResponse>("_links", Links);
            writer.WriteIntValue("maxItems", MaxItems);
        }
    }
}
#pragma warning restore CS0618
