// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TenantLinksResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The children property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Models.LinkResponse? Children { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Models.LinkResponse Children { get; set; }
#endif
        /// <summary>The self property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Models.LinkResponse? Self { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Models.LinkResponse Self { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.TenantLinksResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marain.Tenancy.Client.Models.TenantLinksResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Marain.Tenancy.Client.Models.TenantLinksResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "children", n => { Children = n.GetObjectValue<global::Marain.Tenancy.Client.Models.LinkResponse>(global::Marain.Tenancy.Client.Models.LinkResponse.CreateFromDiscriminatorValue); } },
                { "self", n => { Self = n.GetObjectValue<global::Marain.Tenancy.Client.Models.LinkResponse>(global::Marain.Tenancy.Client.Models.LinkResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Models.LinkResponse>("children", Children);
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Models.LinkResponse>("self", Self);
        }
    }
}
#pragma warning restore CS0618
