// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateTenantJsonPatchEntryOperation
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "add")]
        #pragma warning disable CS1591
        Add,
        #pragma warning restore CS1591
        [EnumMember(Value = "replace")]
        #pragma warning disable CS1591
        Replace,
        #pragma warning restore CS1591
        [EnumMember(Value = "remove")]
        #pragma warning disable CS1591
        Remove,
        #pragma warning restore CS1591
    }
}
