// <auto-generated/>
#pragma warning disable CS0618
using Marain.Tenancy.Client.Item.Marain.Tenant.Children.Item;
using Marain.Tenancy.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Marain.Tenancy.Client.Item.Marain.Tenant.Children
{
    /// <summary>
    /// Builds and executes requests for operations under \{tenantId}\marain\tenant\children
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChildrenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Marain.Tenancy.Client.item.marain.tenant.children.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.Item.WithChildTenantItemRequestBuilder"/></returns>
        public global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.Item.WithChildTenantItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("childTenantId", position);
                return new global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.Item.WithChildTenantItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChildrenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}/marain/tenant/children{?ContinuationToken*,MaxItems*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChildrenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}/marain/tenant/children{?ContinuationToken*,MaxItems*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a paginated list of child tenants.
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.ChildTenantsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Marain.Tenancy.Client.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Marain.Tenancy.Client.Models.ProblemDetails">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Marain.Tenancy.Client.Models.ChildTenantsResponse?> GetAsync(Action<RequestConfiguration<global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Marain.Tenancy.Client.Models.ChildTenantsResponse> GetAsync(Action<RequestConfiguration<global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Marain.Tenancy.Client.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::Marain.Tenancy.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Marain.Tenancy.Client.Models.ChildTenantsResponse>(requestInfo, global::Marain.Tenancy.Client.Models.ChildTenantsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a paginated list of child tenants.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a paginated list of child tenants.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChildrenRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? ContinuationToken { get; set; }
#nullable restore
#else
            public string ContinuationToken { get; set; }
#endif
            public int? MaxItems { get; set; }
        }
    }
}
#pragma warning restore CS0618
