// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Tenancy.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for TenancyService.
    /// </summary>
    public static partial class TenancyServiceExtensions
    {
            /// <summary>
            /// Update a tenant
            /// </summary>
            /// <remarks>
            /// Updates the tenant
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The tenant within which the request should operate
            /// </param>
            /// <param name='body'>
            /// </param>
            public static object UpdateTenant(this ITenancyService operations, string tenantId, object body)
            {
                return operations.UpdateTenantAsync(tenantId, body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update a tenant
            /// </summary>
            /// <remarks>
            /// Updates the tenant
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The tenant within which the request should operate
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> UpdateTenantAsync(this ITenancyService operations, string tenantId, object body, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.UpdateTenantWithHttpMessagesAsync(tenantId, body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets a tenant
            /// </summary>
            /// <remarks>
            /// Gets the tenant
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The tenant within which the request should operate
            /// </param>
            /// <param name='ifNoneMatch'>
            /// The ETag of the last known version.
            /// </param>
            public static object GetTenant(this ITenancyService operations, string tenantId, string ifNoneMatch = default(string))
            {
                return operations.GetTenantAsync(tenantId, ifNoneMatch).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets a tenant
            /// </summary>
            /// <remarks>
            /// Gets the tenant
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The tenant within which the request should operate
            /// </param>
            /// <param name='ifNoneMatch'>
            /// The ETag of the last known version.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetTenantAsync(this ITenancyService operations, string tenantId, string ifNoneMatch = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetTenantWithHttpMessagesAsync(tenantId, ifNoneMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get all child tenants of the current tenant
            /// </summary>
            /// <remarks>
            /// Get all child tenants of the current tenant
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The tenant within which the request should operate
            /// </param>
            /// <param name='continuationToken'>
            /// A continuation token for an operation where more data is available
            /// </param>
            /// <param name='maxItems'>
            /// The maximum number of items to return in the request. Fewer than this
            /// number may be returned.
            /// </param>
            public static object GetChildren(this ITenancyService operations, string tenantId, string continuationToken = default(string), int? maxItems = default(int?))
            {
                return operations.GetChildrenAsync(tenantId, continuationToken, maxItems).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get all child tenants of the current tenant
            /// </summary>
            /// <remarks>
            /// Get all child tenants of the current tenant
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The tenant within which the request should operate
            /// </param>
            /// <param name='continuationToken'>
            /// A continuation token for an operation where more data is available
            /// </param>
            /// <param name='maxItems'>
            /// The maximum number of items to return in the request. Fewer than this
            /// number may be returned.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetChildrenAsync(this ITenancyService operations, string tenantId, string continuationToken = default(string), int? maxItems = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetChildrenWithHttpMessagesAsync(tenantId, continuationToken, maxItems, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a child tenant
            /// </summary>
            /// <remarks>
            /// Creates a child tenant of the parent tenant
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The tenant within which the request should operate
            /// </param>
            public static CreateChildTenantHeaders CreateChildTenant(this ITenancyService operations, string tenantId)
            {
                return operations.CreateChildTenantAsync(tenantId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a child tenant
            /// </summary>
            /// <remarks>
            /// Creates a child tenant of the parent tenant
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The tenant within which the request should operate
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CreateChildTenantHeaders> CreateChildTenantAsync(this ITenancyService operations, string tenantId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateChildTenantWithHttpMessagesAsync(tenantId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Delete a child tenant by ID
            /// </summary>
            /// <remarks>
            /// Deletes a child tenant of the parent tenant by ID
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The tenant within which the request should operate
            /// </param>
            /// <param name='childTenantId'>
            /// The child tenant within the current tenant.
            /// </param>
            public static void DeleteChildTenant(this ITenancyService operations, string tenantId, string childTenantId)
            {
                operations.DeleteChildTenantAsync(tenantId, childTenantId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete a child tenant by ID
            /// </summary>
            /// <remarks>
            /// Deletes a child tenant of the parent tenant by ID
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The tenant within which the request should operate
            /// </param>
            /// <param name='childTenantId'>
            /// The child tenant within the current tenant.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteChildTenantAsync(this ITenancyService operations, string tenantId, string childTenantId, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteChildTenantWithHttpMessagesAsync(tenantId, childTenantId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// View swagger definition for this API
            /// </summary>
            /// <remarks>
            /// View swagger definition for this API
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static object GetSwagger(this ITenancyService operations)
            {
                return operations.GetSwaggerAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// View swagger definition for this API
            /// </summary>
            /// <remarks>
            /// View swagger definition for this API
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetSwaggerAsync(this ITenancyService operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSwaggerWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
