// <auto-generated/>
#pragma warning disable CS0618
using Marain.Tenancy.Client.Item.Marain.Tenant.Children;
using Marain.Tenancy.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Marain.Tenancy.Client.Item.Marain.Tenant
{
    /// <summary>
    /// Builds and executes requests for operations under \{tenantId}\marain\tenant
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TenantRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The children property</summary>
        public global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder Children
        {
            get => new global::Marain.Tenancy.Client.Item.Marain.Tenant.Children.ChildrenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Item.Marain.Tenant.TenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}/marain/tenant", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Item.Marain.Tenant.TenantRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}/marain/tenant", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves detailed information about a specific tenant.
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.TenantResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Marain.Tenancy.Client.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Marain.Tenancy.Client.Models.ProblemDetails">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Marain.Tenancy.Client.Models.TenantResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Marain.Tenancy.Client.Models.TenantResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Marain.Tenancy.Client.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::Marain.Tenancy.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Marain.Tenancy.Client.Models.TenantResponse>(requestInfo, global::Marain.Tenancy.Client.Models.TenantResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates tenant properties using JSON Patch operations.
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.TenantResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Marain.Tenancy.Client.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Marain.Tenancy.Client.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::Marain.Tenancy.Client.Models.ProblemDetails">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Marain.Tenancy.Client.Models.TenantResponse?> PatchAsync(List<global::Marain.Tenancy.Client.Models.UpdateTenantJsonPatchEntry> body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Marain.Tenancy.Client.Models.TenantResponse> PatchAsync(List<global::Marain.Tenancy.Client.Models.UpdateTenantJsonPatchEntry> body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Marain.Tenancy.Client.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::Marain.Tenancy.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "422", global::Marain.Tenancy.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Marain.Tenancy.Client.Models.TenantResponse>(requestInfo, global::Marain.Tenancy.Client.Models.TenantResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new child tenant under the specified parent tenant.
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.TenantResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Marain.Tenancy.Client.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Marain.Tenancy.Client.Models.ProblemDetails">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Marain.Tenancy.Client.Models.TenantResponse?> PostAsync(global::Marain.Tenancy.Client.Models.CreateChildTenantRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Marain.Tenancy.Client.Models.TenantResponse> PostAsync(global::Marain.Tenancy.Client.Models.CreateChildTenantRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Marain.Tenancy.Client.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::Marain.Tenancy.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Marain.Tenancy.Client.Models.TenantResponse>(requestInfo, global::Marain.Tenancy.Client.Models.TenantResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves detailed information about a specific tenant.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates tenant properties using JSON Patch operations.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(List<global::Marain.Tenancy.Client.Models.UpdateTenantJsonPatchEntry> body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(List<global::Marain.Tenancy.Client.Models.UpdateTenantJsonPatchEntry> body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Creates a new child tenant under the specified parent tenant.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Marain.Tenancy.Client.Models.CreateChildTenantRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Marain.Tenancy.Client.Models.CreateChildTenantRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Item.Marain.Tenant.TenantRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Marain.Tenancy.Client.Item.Marain.Tenant.TenantRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Marain.Tenancy.Client.Item.Marain.Tenant.TenantRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
