// <auto-generated/>
#pragma warning disable CS0618
using Marain.Tenancy.Client.Internal.Item.Marain;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Marain.Tenancy.Client.Internal.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \{tenantId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTenantItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The marain property</summary>
        public global::Marain.Tenancy.Client.Internal.Item.Marain.MarainRequestBuilder Marain
        {
            get => new global::Marain.Tenancy.Client.Internal.Item.Marain.MarainRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Internal.Item.WithTenantItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Internal.Item.WithTenantItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTenantItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
