// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Calendar : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The algorithmType property</summary>
        public global::Marain.Tenancy.Client.Models.CalendarAlgorithmType? AlgorithmType { get; set; }
        /// <summary>The eras property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Eras { get; private set; }
#nullable restore
#else
        public List<int?> Eras { get; private set; }
#endif
        /// <summary>The isReadOnly property</summary>
        public bool? IsReadOnly { get; private set; }
        /// <summary>The maxSupportedDateTime property</summary>
        public DateTimeOffset? MaxSupportedDateTime { get; private set; }
        /// <summary>The minSupportedDateTime property</summary>
        public DateTimeOffset? MinSupportedDateTime { get; private set; }
        /// <summary>The twoDigitYearMax property</summary>
        public int? TwoDigitYearMax { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.Calendar"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marain.Tenancy.Client.Models.Calendar CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Marain.Tenancy.Client.Models.Calendar();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "algorithmType", n => { AlgorithmType = n.GetEnumValue<global::Marain.Tenancy.Client.Models.CalendarAlgorithmType>(); } },
                { "eras", n => { Eras = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "isReadOnly", n => { IsReadOnly = n.GetBoolValue(); } },
                { "maxSupportedDateTime", n => { MaxSupportedDateTime = n.GetDateTimeOffsetValue(); } },
                { "minSupportedDateTime", n => { MinSupportedDateTime = n.GetDateTimeOffsetValue(); } },
                { "twoDigitYearMax", n => { TwoDigitYearMax = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Marain.Tenancy.Client.Models.CalendarAlgorithmType>("algorithmType", AlgorithmType);
            writer.WriteIntValue("twoDigitYearMax", TwoDigitYearMax);
        }
    }
}
#pragma warning restore CS0618
