// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CalendarWeekRule
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "firstDay")]
        #pragma warning disable CS1591
        FirstDay,
        #pragma warning restore CS1591
        [EnumMember(Value = "firstFullWeek")]
        #pragma warning disable CS1591
        FirstFullWeek,
        #pragma warning restore CS1591
        [EnumMember(Value = "firstFourDayWeek")]
        #pragma warning disable CS1591
        FirstFourDayWeek,
        #pragma warning restore CS1591
    }
}
