// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CalendarAlgorithmType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "solarCalendar")]
        #pragma warning disable CS1591
        SolarCalendar,
        #pragma warning restore CS1591
        [EnumMember(Value = "lunarCalendar")]
        #pragma warning disable CS1591
        LunarCalendar,
        #pragma warning restore CS1591
        [EnumMember(Value = "lunisolarCalendar")]
        #pragma warning disable CS1591
        LunisolarCalendar,
        #pragma warning restore CS1591
    }
}
