// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Tenancy.Client.Models
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A resource containing links for the child tenants.
    /// </summary>
    public partial class ChildTenants : Resource
    {
        /// <summary>
        /// Initializes a new instance of the ChildTenants class.
        /// </summary>
        public ChildTenants()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ChildTenants class.
        /// </summary>
        /// <param name="_links">Hyperlink</param>
        public ChildTenants(IDictionary<string, object> _links = default(IDictionary<string, object>), IDictionary<string, object> _embedded = default(IDictionary<string, object>))
            : base(_links, _embedded)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
