// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Tenancy.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for createChildTenant operation.
    /// </summary>
    public partial class CreateChildTenantHeaders
    {
        /// <summary>
        /// Initializes a new instance of the CreateChildTenantHeaders class.
        /// </summary>
        public CreateChildTenantHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateChildTenantHeaders class.
        /// </summary>
        /// <param name="location">The location of the created tenant</param>
        public CreateChildTenantHeaders(string location = default(string))
        {
            Location = location;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the location of the created tenant
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

    }
}
