// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CultureTypes
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "neutralCultures")]
        #pragma warning disable CS1591
        NeutralCultures,
        #pragma warning restore CS1591
        [EnumMember(Value = "specificCultures")]
        #pragma warning disable CS1591
        SpecificCultures,
        #pragma warning restore CS1591
        [EnumMember(Value = "installedWin32Cultures")]
        #pragma warning disable CS1591
        InstalledWin32Cultures,
        #pragma warning restore CS1591
        [EnumMember(Value = "allCultures")]
        #pragma warning disable CS1591
        AllCultures,
        #pragma warning restore CS1591
        [EnumMember(Value = "userCustomCulture")]
        #pragma warning disable CS1591
        UserCustomCulture,
        #pragma warning restore CS1591
        [EnumMember(Value = "replacementCultures")]
        #pragma warning disable CS1591
        ReplacementCultures,
        #pragma warning restore CS1591
        [EnumMember(Value = "windowsOnlyCultures")]
        #pragma warning disable CS1591
        WindowsOnlyCultures,
        #pragma warning restore CS1591
        [EnumMember(Value = "frameworkCultures")]
        #pragma warning disable CS1591
        FrameworkCultures,
        #pragma warning restore CS1591
    }
}
