// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CultureInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The calendar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Models.Calendar? Calendar { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Models.Calendar Calendar { get; set; }
#endif
        /// <summary>The compareInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Models.CompareInfo? CompareInfo { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Models.CompareInfo CompareInfo { get; set; }
#endif
        /// <summary>The cultureTypes property</summary>
        public global::Marain.Tenancy.Client.Models.CultureTypes? CultureTypes { get; set; }
        /// <summary>The dateTimeFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Models.DateTimeFormatInfo? DateTimeFormat { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Models.DateTimeFormatInfo DateTimeFormat { get; set; }
#endif
        /// <summary>The displayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; private set; }
#nullable restore
#else
        public string DisplayName { get; private set; }
#endif
        /// <summary>The englishName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnglishName { get; private set; }
#nullable restore
#else
        public string EnglishName { get; private set; }
#endif
        /// <summary>The ietfLanguageTag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IetfLanguageTag { get; private set; }
#nullable restore
#else
        public string IetfLanguageTag { get; private set; }
#endif
        /// <summary>The isNeutralCulture property</summary>
        public bool? IsNeutralCulture { get; private set; }
        /// <summary>The isReadOnly property</summary>
        public bool? IsReadOnly { get; private set; }
        /// <summary>The keyboardLayoutId property</summary>
        public int? KeyboardLayoutId { get; private set; }
        /// <summary>The lcid property</summary>
        public int? Lcid { get; private set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nativeName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NativeName { get; private set; }
#nullable restore
#else
        public string NativeName { get; private set; }
#endif
        /// <summary>The numberFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Models.NumberFormatInfo? NumberFormat { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Models.NumberFormatInfo NumberFormat { get; set; }
#endif
        /// <summary>The optionalCalendars property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Marain.Tenancy.Client.Models.Calendar>? OptionalCalendars { get; private set; }
#nullable restore
#else
        public List<global::Marain.Tenancy.Client.Models.Calendar> OptionalCalendars { get; private set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Models.CultureInfo? Parent { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Models.CultureInfo Parent { get; set; }
#endif
        /// <summary>The textInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Models.TextInfo? TextInfo { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Models.TextInfo TextInfo { get; set; }
#endif
        /// <summary>The threeLetterISOLanguageName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThreeLetterISOLanguageName { get; private set; }
#nullable restore
#else
        public string ThreeLetterISOLanguageName { get; private set; }
#endif
        /// <summary>The threeLetterWindowsLanguageName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThreeLetterWindowsLanguageName { get; private set; }
#nullable restore
#else
        public string ThreeLetterWindowsLanguageName { get; private set; }
#endif
        /// <summary>The twoLetterISOLanguageName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TwoLetterISOLanguageName { get; private set; }
#nullable restore
#else
        public string TwoLetterISOLanguageName { get; private set; }
#endif
        /// <summary>The useUserOverride property</summary>
        public bool? UseUserOverride { get; private set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.CultureInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marain.Tenancy.Client.Models.CultureInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Marain.Tenancy.Client.Models.CultureInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calendar", n => { Calendar = n.GetObjectValue<global::Marain.Tenancy.Client.Models.Calendar>(global::Marain.Tenancy.Client.Models.Calendar.CreateFromDiscriminatorValue); } },
                { "compareInfo", n => { CompareInfo = n.GetObjectValue<global::Marain.Tenancy.Client.Models.CompareInfo>(global::Marain.Tenancy.Client.Models.CompareInfo.CreateFromDiscriminatorValue); } },
                { "cultureTypes", n => { CultureTypes = n.GetEnumValue<global::Marain.Tenancy.Client.Models.CultureTypes>(); } },
                { "dateTimeFormat", n => { DateTimeFormat = n.GetObjectValue<global::Marain.Tenancy.Client.Models.DateTimeFormatInfo>(global::Marain.Tenancy.Client.Models.DateTimeFormatInfo.CreateFromDiscriminatorValue); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "englishName", n => { EnglishName = n.GetStringValue(); } },
                { "ietfLanguageTag", n => { IetfLanguageTag = n.GetStringValue(); } },
                { "isNeutralCulture", n => { IsNeutralCulture = n.GetBoolValue(); } },
                { "isReadOnly", n => { IsReadOnly = n.GetBoolValue(); } },
                { "keyboardLayoutId", n => { KeyboardLayoutId = n.GetIntValue(); } },
                { "lcid", n => { Lcid = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nativeName", n => { NativeName = n.GetStringValue(); } },
                { "numberFormat", n => { NumberFormat = n.GetObjectValue<global::Marain.Tenancy.Client.Models.NumberFormatInfo>(global::Marain.Tenancy.Client.Models.NumberFormatInfo.CreateFromDiscriminatorValue); } },
                { "optionalCalendars", n => { OptionalCalendars = n.GetCollectionOfObjectValues<global::Marain.Tenancy.Client.Models.Calendar>(global::Marain.Tenancy.Client.Models.Calendar.CreateFromDiscriminatorValue)?.AsList(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::Marain.Tenancy.Client.Models.CultureInfo>(global::Marain.Tenancy.Client.Models.CultureInfo.CreateFromDiscriminatorValue); } },
                { "textInfo", n => { TextInfo = n.GetObjectValue<global::Marain.Tenancy.Client.Models.TextInfo>(global::Marain.Tenancy.Client.Models.TextInfo.CreateFromDiscriminatorValue); } },
                { "threeLetterISOLanguageName", n => { ThreeLetterISOLanguageName = n.GetStringValue(); } },
                { "threeLetterWindowsLanguageName", n => { ThreeLetterWindowsLanguageName = n.GetStringValue(); } },
                { "twoLetterISOLanguageName", n => { TwoLetterISOLanguageName = n.GetStringValue(); } },
                { "useUserOverride", n => { UseUserOverride = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Models.Calendar>("calendar", Calendar);
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Models.CompareInfo>("compareInfo", CompareInfo);
            writer.WriteEnumValue<global::Marain.Tenancy.Client.Models.CultureTypes>("cultureTypes", CultureTypes);
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Models.DateTimeFormatInfo>("dateTimeFormat", DateTimeFormat);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Models.NumberFormatInfo>("numberFormat", NumberFormat);
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Models.CultureInfo>("parent", Parent);
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Models.TextInfo>("textInfo", TextInfo);
        }
    }
}
#pragma warning restore CS0618
