// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DateTimeFormatInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The abbreviatedDayNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AbbreviatedDayNames { get; set; }
#nullable restore
#else
        public List<string> AbbreviatedDayNames { get; set; }
#endif
        /// <summary>The abbreviatedMonthGenitiveNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AbbreviatedMonthGenitiveNames { get; set; }
#nullable restore
#else
        public List<string> AbbreviatedMonthGenitiveNames { get; set; }
#endif
        /// <summary>The abbreviatedMonthNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AbbreviatedMonthNames { get; set; }
#nullable restore
#else
        public List<string> AbbreviatedMonthNames { get; set; }
#endif
        /// <summary>The amDesignator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AmDesignator { get; set; }
#nullable restore
#else
        public string AmDesignator { get; set; }
#endif
        /// <summary>The calendar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Models.Calendar? Calendar { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Models.Calendar Calendar { get; set; }
#endif
        /// <summary>The calendarWeekRule property</summary>
        public global::Marain.Tenancy.Client.Models.CalendarWeekRule? CalendarWeekRule { get; set; }
        /// <summary>The dateSeparator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateSeparator { get; set; }
#nullable restore
#else
        public string DateSeparator { get; set; }
#endif
        /// <summary>The dayNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DayNames { get; set; }
#nullable restore
#else
        public List<string> DayNames { get; set; }
#endif
        /// <summary>The firstDayOfWeek property</summary>
        public global::Marain.Tenancy.Client.Models.DayOfWeekObject? FirstDayOfWeek { get; set; }
        /// <summary>The fullDateTimePattern property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullDateTimePattern { get; set; }
#nullable restore
#else
        public string FullDateTimePattern { get; set; }
#endif
        /// <summary>The isReadOnly property</summary>
        public bool? IsReadOnly { get; private set; }
        /// <summary>The longDatePattern property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LongDatePattern { get; set; }
#nullable restore
#else
        public string LongDatePattern { get; set; }
#endif
        /// <summary>The longTimePattern property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LongTimePattern { get; set; }
#nullable restore
#else
        public string LongTimePattern { get; set; }
#endif
        /// <summary>The monthDayPattern property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MonthDayPattern { get; set; }
#nullable restore
#else
        public string MonthDayPattern { get; set; }
#endif
        /// <summary>The monthGenitiveNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MonthGenitiveNames { get; set; }
#nullable restore
#else
        public List<string> MonthGenitiveNames { get; set; }
#endif
        /// <summary>The monthNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MonthNames { get; set; }
#nullable restore
#else
        public List<string> MonthNames { get; set; }
#endif
        /// <summary>The nativeCalendarName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NativeCalendarName { get; private set; }
#nullable restore
#else
        public string NativeCalendarName { get; private set; }
#endif
        /// <summary>The pmDesignator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PmDesignator { get; set; }
#nullable restore
#else
        public string PmDesignator { get; set; }
#endif
        /// <summary>The rfC1123Pattern property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RfC1123Pattern { get; private set; }
#nullable restore
#else
        public string RfC1123Pattern { get; private set; }
#endif
        /// <summary>The shortDatePattern property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShortDatePattern { get; set; }
#nullable restore
#else
        public string ShortDatePattern { get; set; }
#endif
        /// <summary>The shortestDayNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ShortestDayNames { get; set; }
#nullable restore
#else
        public List<string> ShortestDayNames { get; set; }
#endif
        /// <summary>The shortTimePattern property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShortTimePattern { get; set; }
#nullable restore
#else
        public string ShortTimePattern { get; set; }
#endif
        /// <summary>The sortableDateTimePattern property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SortableDateTimePattern { get; private set; }
#nullable restore
#else
        public string SortableDateTimePattern { get; private set; }
#endif
        /// <summary>The timeSeparator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeSeparator { get; set; }
#nullable restore
#else
        public string TimeSeparator { get; set; }
#endif
        /// <summary>The universalSortableDateTimePattern property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UniversalSortableDateTimePattern { get; private set; }
#nullable restore
#else
        public string UniversalSortableDateTimePattern { get; private set; }
#endif
        /// <summary>The yearMonthPattern property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? YearMonthPattern { get; set; }
#nullable restore
#else
        public string YearMonthPattern { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.DateTimeFormatInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marain.Tenancy.Client.Models.DateTimeFormatInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Marain.Tenancy.Client.Models.DateTimeFormatInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "abbreviatedDayNames", n => { AbbreviatedDayNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "abbreviatedMonthGenitiveNames", n => { AbbreviatedMonthGenitiveNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "abbreviatedMonthNames", n => { AbbreviatedMonthNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "amDesignator", n => { AmDesignator = n.GetStringValue(); } },
                { "calendar", n => { Calendar = n.GetObjectValue<global::Marain.Tenancy.Client.Models.Calendar>(global::Marain.Tenancy.Client.Models.Calendar.CreateFromDiscriminatorValue); } },
                { "calendarWeekRule", n => { CalendarWeekRule = n.GetEnumValue<global::Marain.Tenancy.Client.Models.CalendarWeekRule>(); } },
                { "dateSeparator", n => { DateSeparator = n.GetStringValue(); } },
                { "dayNames", n => { DayNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "firstDayOfWeek", n => { FirstDayOfWeek = n.GetEnumValue<global::Marain.Tenancy.Client.Models.DayOfWeekObject>(); } },
                { "fullDateTimePattern", n => { FullDateTimePattern = n.GetStringValue(); } },
                { "isReadOnly", n => { IsReadOnly = n.GetBoolValue(); } },
                { "longDatePattern", n => { LongDatePattern = n.GetStringValue(); } },
                { "longTimePattern", n => { LongTimePattern = n.GetStringValue(); } },
                { "monthDayPattern", n => { MonthDayPattern = n.GetStringValue(); } },
                { "monthGenitiveNames", n => { MonthGenitiveNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "monthNames", n => { MonthNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "nativeCalendarName", n => { NativeCalendarName = n.GetStringValue(); } },
                { "pmDesignator", n => { PmDesignator = n.GetStringValue(); } },
                { "rfC1123Pattern", n => { RfC1123Pattern = n.GetStringValue(); } },
                { "shortDatePattern", n => { ShortDatePattern = n.GetStringValue(); } },
                { "shortTimePattern", n => { ShortTimePattern = n.GetStringValue(); } },
                { "shortestDayNames", n => { ShortestDayNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sortableDateTimePattern", n => { SortableDateTimePattern = n.GetStringValue(); } },
                { "timeSeparator", n => { TimeSeparator = n.GetStringValue(); } },
                { "universalSortableDateTimePattern", n => { UniversalSortableDateTimePattern = n.GetStringValue(); } },
                { "yearMonthPattern", n => { YearMonthPattern = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("abbreviatedDayNames", AbbreviatedDayNames);
            writer.WriteCollectionOfPrimitiveValues<string>("abbreviatedMonthGenitiveNames", AbbreviatedMonthGenitiveNames);
            writer.WriteCollectionOfPrimitiveValues<string>("abbreviatedMonthNames", AbbreviatedMonthNames);
            writer.WriteStringValue("amDesignator", AmDesignator);
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Models.Calendar>("calendar", Calendar);
            writer.WriteEnumValue<global::Marain.Tenancy.Client.Models.CalendarWeekRule>("calendarWeekRule", CalendarWeekRule);
            writer.WriteStringValue("dateSeparator", DateSeparator);
            writer.WriteCollectionOfPrimitiveValues<string>("dayNames", DayNames);
            writer.WriteEnumValue<global::Marain.Tenancy.Client.Models.DayOfWeekObject>("firstDayOfWeek", FirstDayOfWeek);
            writer.WriteStringValue("fullDateTimePattern", FullDateTimePattern);
            writer.WriteStringValue("longDatePattern", LongDatePattern);
            writer.WriteStringValue("longTimePattern", LongTimePattern);
            writer.WriteStringValue("monthDayPattern", MonthDayPattern);
            writer.WriteCollectionOfPrimitiveValues<string>("monthGenitiveNames", MonthGenitiveNames);
            writer.WriteCollectionOfPrimitiveValues<string>("monthNames", MonthNames);
            writer.WriteStringValue("pmDesignator", PmDesignator);
            writer.WriteStringValue("shortDatePattern", ShortDatePattern);
            writer.WriteCollectionOfPrimitiveValues<string>("shortestDayNames", ShortestDayNames);
            writer.WriteStringValue("shortTimePattern", ShortTimePattern);
            writer.WriteStringValue("timeSeparator", TimeSeparator);
            writer.WriteStringValue("yearMonthPattern", YearMonthPattern);
        }
    }
}
#pragma warning restore CS0618
