// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DigitShapes
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "context")]
        #pragma warning disable CS1591
        Context,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "nativeNational")]
        #pragma warning disable CS1591
        NativeNational,
        #pragma warning restore CS1591
    }
}
