// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Tenancy.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for getTenant operation.
    /// </summary>
    public partial class GetTenantHeaders
    {
        /// <summary>
        /// Initializes a new instance of the GetTenantHeaders class.
        /// </summary>
        public GetTenantHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetTenantHeaders class.
        /// </summary>
        /// <param name="cacheControl">Caching instructions for clients</param>
        /// <param name="eTag">The etag for the updated tenant</param>
        public GetTenantHeaders(string cacheControl = default(string), string eTag = default(string))
        {
            CacheControl = cacheControl;
            ETag = eTag;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets caching instructions for clients
        /// </summary>
        [JsonProperty(PropertyName = "Cache-Control")]
        public string CacheControl { get; set; }

        /// <summary>
        /// Gets or sets the etag for the updated tenant
        /// </summary>
        [JsonProperty(PropertyName = "ETag")]
        public string ETag { get; set; }

    }
}
