// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NumberFormatInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The currencyDecimalDigits property</summary>
        public int? CurrencyDecimalDigits { get; set; }
        /// <summary>The currencyDecimalSeparator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyDecimalSeparator { get; set; }
#nullable restore
#else
        public string CurrencyDecimalSeparator { get; set; }
#endif
        /// <summary>The currencyGroupSeparator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyGroupSeparator { get; set; }
#nullable restore
#else
        public string CurrencyGroupSeparator { get; set; }
#endif
        /// <summary>The currencyGroupSizes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? CurrencyGroupSizes { get; set; }
#nullable restore
#else
        public List<int?> CurrencyGroupSizes { get; set; }
#endif
        /// <summary>The currencyNegativePattern property</summary>
        public int? CurrencyNegativePattern { get; set; }
        /// <summary>The currencyPositivePattern property</summary>
        public int? CurrencyPositivePattern { get; set; }
        /// <summary>The currencySymbol property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencySymbol { get; set; }
#nullable restore
#else
        public string CurrencySymbol { get; set; }
#endif
        /// <summary>The digitSubstitution property</summary>
        public global::Marain.Tenancy.Client.Models.DigitShapes? DigitSubstitution { get; set; }
        /// <summary>The isReadOnly property</summary>
        public bool? IsReadOnly { get; private set; }
        /// <summary>The naNSymbol property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NaNSymbol { get; set; }
#nullable restore
#else
        public string NaNSymbol { get; set; }
#endif
        /// <summary>The nativeDigits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NativeDigits { get; set; }
#nullable restore
#else
        public List<string> NativeDigits { get; set; }
#endif
        /// <summary>The negativeInfinitySymbol property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NegativeInfinitySymbol { get; set; }
#nullable restore
#else
        public string NegativeInfinitySymbol { get; set; }
#endif
        /// <summary>The negativeSign property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NegativeSign { get; set; }
#nullable restore
#else
        public string NegativeSign { get; set; }
#endif
        /// <summary>The numberDecimalDigits property</summary>
        public int? NumberDecimalDigits { get; set; }
        /// <summary>The numberDecimalSeparator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumberDecimalSeparator { get; set; }
#nullable restore
#else
        public string NumberDecimalSeparator { get; set; }
#endif
        /// <summary>The numberGroupSeparator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumberGroupSeparator { get; set; }
#nullable restore
#else
        public string NumberGroupSeparator { get; set; }
#endif
        /// <summary>The numberGroupSizes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? NumberGroupSizes { get; set; }
#nullable restore
#else
        public List<int?> NumberGroupSizes { get; set; }
#endif
        /// <summary>The numberNegativePattern property</summary>
        public int? NumberNegativePattern { get; set; }
        /// <summary>The percentDecimalDigits property</summary>
        public int? PercentDecimalDigits { get; set; }
        /// <summary>The percentDecimalSeparator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PercentDecimalSeparator { get; set; }
#nullable restore
#else
        public string PercentDecimalSeparator { get; set; }
#endif
        /// <summary>The percentGroupSeparator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PercentGroupSeparator { get; set; }
#nullable restore
#else
        public string PercentGroupSeparator { get; set; }
#endif
        /// <summary>The percentGroupSizes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? PercentGroupSizes { get; set; }
#nullable restore
#else
        public List<int?> PercentGroupSizes { get; set; }
#endif
        /// <summary>The percentNegativePattern property</summary>
        public int? PercentNegativePattern { get; set; }
        /// <summary>The percentPositivePattern property</summary>
        public int? PercentPositivePattern { get; set; }
        /// <summary>The percentSymbol property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PercentSymbol { get; set; }
#nullable restore
#else
        public string PercentSymbol { get; set; }
#endif
        /// <summary>The perMilleSymbol property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PerMilleSymbol { get; set; }
#nullable restore
#else
        public string PerMilleSymbol { get; set; }
#endif
        /// <summary>The positiveInfinitySymbol property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PositiveInfinitySymbol { get; set; }
#nullable restore
#else
        public string PositiveInfinitySymbol { get; set; }
#endif
        /// <summary>The positiveSign property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PositiveSign { get; set; }
#nullable restore
#else
        public string PositiveSign { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.NumberFormatInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marain.Tenancy.Client.Models.NumberFormatInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Marain.Tenancy.Client.Models.NumberFormatInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currencyDecimalDigits", n => { CurrencyDecimalDigits = n.GetIntValue(); } },
                { "currencyDecimalSeparator", n => { CurrencyDecimalSeparator = n.GetStringValue(); } },
                { "currencyGroupSeparator", n => { CurrencyGroupSeparator = n.GetStringValue(); } },
                { "currencyGroupSizes", n => { CurrencyGroupSizes = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "currencyNegativePattern", n => { CurrencyNegativePattern = n.GetIntValue(); } },
                { "currencyPositivePattern", n => { CurrencyPositivePattern = n.GetIntValue(); } },
                { "currencySymbol", n => { CurrencySymbol = n.GetStringValue(); } },
                { "digitSubstitution", n => { DigitSubstitution = n.GetEnumValue<global::Marain.Tenancy.Client.Models.DigitShapes>(); } },
                { "isReadOnly", n => { IsReadOnly = n.GetBoolValue(); } },
                { "naNSymbol", n => { NaNSymbol = n.GetStringValue(); } },
                { "nativeDigits", n => { NativeDigits = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "negativeInfinitySymbol", n => { NegativeInfinitySymbol = n.GetStringValue(); } },
                { "negativeSign", n => { NegativeSign = n.GetStringValue(); } },
                { "numberDecimalDigits", n => { NumberDecimalDigits = n.GetIntValue(); } },
                { "numberDecimalSeparator", n => { NumberDecimalSeparator = n.GetStringValue(); } },
                { "numberGroupSeparator", n => { NumberGroupSeparator = n.GetStringValue(); } },
                { "numberGroupSizes", n => { NumberGroupSizes = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "numberNegativePattern", n => { NumberNegativePattern = n.GetIntValue(); } },
                { "perMilleSymbol", n => { PerMilleSymbol = n.GetStringValue(); } },
                { "percentDecimalDigits", n => { PercentDecimalDigits = n.GetIntValue(); } },
                { "percentDecimalSeparator", n => { PercentDecimalSeparator = n.GetStringValue(); } },
                { "percentGroupSeparator", n => { PercentGroupSeparator = n.GetStringValue(); } },
                { "percentGroupSizes", n => { PercentGroupSizes = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "percentNegativePattern", n => { PercentNegativePattern = n.GetIntValue(); } },
                { "percentPositivePattern", n => { PercentPositivePattern = n.GetIntValue(); } },
                { "percentSymbol", n => { PercentSymbol = n.GetStringValue(); } },
                { "positiveInfinitySymbol", n => { PositiveInfinitySymbol = n.GetStringValue(); } },
                { "positiveSign", n => { PositiveSign = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("currencyDecimalDigits", CurrencyDecimalDigits);
            writer.WriteStringValue("currencyDecimalSeparator", CurrencyDecimalSeparator);
            writer.WriteStringValue("currencyGroupSeparator", CurrencyGroupSeparator);
            writer.WriteCollectionOfPrimitiveValues<int?>("currencyGroupSizes", CurrencyGroupSizes);
            writer.WriteIntValue("currencyNegativePattern", CurrencyNegativePattern);
            writer.WriteIntValue("currencyPositivePattern", CurrencyPositivePattern);
            writer.WriteStringValue("currencySymbol", CurrencySymbol);
            writer.WriteEnumValue<global::Marain.Tenancy.Client.Models.DigitShapes>("digitSubstitution", DigitSubstitution);
            writer.WriteStringValue("naNSymbol", NaNSymbol);
            writer.WriteCollectionOfPrimitiveValues<string>("nativeDigits", NativeDigits);
            writer.WriteStringValue("negativeInfinitySymbol", NegativeInfinitySymbol);
            writer.WriteStringValue("negativeSign", NegativeSign);
            writer.WriteIntValue("numberDecimalDigits", NumberDecimalDigits);
            writer.WriteStringValue("numberDecimalSeparator", NumberDecimalSeparator);
            writer.WriteStringValue("numberGroupSeparator", NumberGroupSeparator);
            writer.WriteCollectionOfPrimitiveValues<int?>("numberGroupSizes", NumberGroupSizes);
            writer.WriteIntValue("numberNegativePattern", NumberNegativePattern);
            writer.WriteIntValue("percentDecimalDigits", PercentDecimalDigits);
            writer.WriteStringValue("percentDecimalSeparator", PercentDecimalSeparator);
            writer.WriteStringValue("percentGroupSeparator", PercentGroupSeparator);
            writer.WriteCollectionOfPrimitiveValues<int?>("percentGroupSizes", PercentGroupSizes);
            writer.WriteIntValue("percentNegativePattern", PercentNegativePattern);
            writer.WriteIntValue("percentPositivePattern", PercentPositivePattern);
            writer.WriteStringValue("percentSymbol", PercentSymbol);
            writer.WriteStringValue("perMilleSymbol", PerMilleSymbol);
            writer.WriteStringValue("positiveInfinitySymbol", PositiveInfinitySymbol);
            writer.WriteStringValue("positiveSign", PositiveSign);
        }
    }
}
#pragma warning restore CS0618
