// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marain.Tenancy.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TextInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ansiCodePage property</summary>
        public int? AnsiCodePage { get; private set; }
        /// <summary>The cultureName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CultureName { get; private set; }
#nullable restore
#else
        public string CultureName { get; private set; }
#endif
        /// <summary>The ebcdicCodePage property</summary>
        public int? EbcdicCodePage { get; private set; }
        /// <summary>The isReadOnly property</summary>
        public bool? IsReadOnly { get; private set; }
        /// <summary>The isRightToLeft property</summary>
        public bool? IsRightToLeft { get; private set; }
        /// <summary>The lcid property</summary>
        public int? Lcid { get; private set; }
        /// <summary>The listSeparator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ListSeparator { get; set; }
#nullable restore
#else
        public string ListSeparator { get; set; }
#endif
        /// <summary>The macCodePage property</summary>
        public int? MacCodePage { get; private set; }
        /// <summary>The oemCodePage property</summary>
        public int? OemCodePage { get; private set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Models.TextInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marain.Tenancy.Client.Models.TextInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Marain.Tenancy.Client.Models.TextInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ansiCodePage", n => { AnsiCodePage = n.GetIntValue(); } },
                { "cultureName", n => { CultureName = n.GetStringValue(); } },
                { "ebcdicCodePage", n => { EbcdicCodePage = n.GetIntValue(); } },
                { "isReadOnly", n => { IsReadOnly = n.GetBoolValue(); } },
                { "isRightToLeft", n => { IsRightToLeft = n.GetBoolValue(); } },
                { "lcid", n => { Lcid = n.GetIntValue(); } },
                { "listSeparator", n => { ListSeparator = n.GetStringValue(); } },
                { "macCodePage", n => { MacCodePage = n.GetIntValue(); } },
                { "oemCodePage", n => { OemCodePage = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("listSeparator", ListSeparator);
        }
    }
}
#pragma warning restore CS0618
