// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Tenancy.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An operation describing one change to a tenant as part of an
    /// UpdateTenantJsonPatchArray
    /// </summary>
    public partial class UpdateTenantJsonPatchEntry
    {
        /// <summary>
        /// Initializes a new instance of the UpdateTenantJsonPatchEntry class.
        /// </summary>
        public UpdateTenantJsonPatchEntry()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateTenantJsonPatchEntry class.
        /// </summary>
        /// <param name="path">A JSON-Pointer. Either /name or
        /// /properties/propertyName</param>
        /// <param name="op">The operation to be performed. Possible values
        /// include: 'add', 'replace', 'remove'</param>
        /// <param name="value">The value to add or set</param>
        public UpdateTenantJsonPatchEntry(string path, string op, object value = default(object))
        {
            Path = path;
            Op = op;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a JSON-Pointer. Either /name or
        /// /properties/propertyName
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; set; }

        /// <summary>
        /// Gets or sets the operation to be performed. Possible values
        /// include: 'add', 'replace', 'remove'
        /// </summary>
        [JsonProperty(PropertyName = "op")]
        public string Op { get; set; }

        /// <summary>
        /// Gets or sets the value to add or set
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public object Value { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Path == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Path");
            }
            if (Op == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Op");
            }
        }
    }
}
