// <auto-generated/>
#pragma warning disable CS0618
using Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.Item;
using Marain.Tenancy.Client.Internal.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children
{
    /// <summary>
    /// Builds and executes requests for operations under \{tenantId}\marain\tenant\children
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChildrenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Marain.Tenancy.Client.Internal.item.marain.tenant.children.item collection</summary>
        /// <param name="position">The child tenant within the current tenant.</param>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.Item.WithChildTenantItemRequestBuilder"/></returns>
        public global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.Item.WithChildTenantItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("childTenantId", position);
                return new global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.Item.WithChildTenantItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChildrenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}/marain/tenant/children?tenantName={tenantName}{&continuationToken*,maxItems*,wellKnownChildTenantGuid*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChildrenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/{tenantId}/marain/tenant/children?tenantName={tenantName}{&continuationToken*,maxItems*,wellKnownChildTenantGuid*}", rawUrl)
        {
        }
        /// <summary>
        /// Get all child tenants of the current tenant
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Internal.Models.Resource"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Marain.Tenancy.Client.Internal.Models.Resource?> GetAsync(Action<RequestConfiguration<global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Marain.Tenancy.Client.Internal.Models.Resource> GetAsync(Action<RequestConfiguration<global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Marain.Tenancy.Client.Internal.Models.Resource>(requestInfo, global::Marain.Tenancy.Client.Internal.Models.Resource.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a child tenant of the parent tenant
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(Action<RequestConfiguration<global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(Action<RequestConfiguration<global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get all child tenants of the current tenant
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/{tenantId}/marain/tenant/children{?continuationToken*,maxItems*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a child tenant of the parent tenant
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/{tenantId}/marain/tenant/children?tenantName={tenantName}{&wellKnownChildTenantGuid*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get all child tenants of the current tenant
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChildrenRequestBuilderGetQueryParameters 
        {
            /// <summary>A continuation token for an operation where more data is available</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("continuationToken")]
            public string? ContinuationToken { get; set; }
#nullable restore
#else
            [QueryParameter("continuationToken")]
            public string ContinuationToken { get; set; }
#endif
            /// <summary>The maximum number of items to return in the request. Fewer than this number may be returned.</summary>
            [QueryParameter("maxItems")]
            public int? MaxItems { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChildrenRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Creates a child tenant of the parent tenant
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChildrenRequestBuilderPostQueryParameters 
        {
            /// <summary>The name for the new tenant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tenantName")]
            public string? TenantName { get; set; }
#nullable restore
#else
            [QueryParameter("tenantName")]
            public string TenantName { get; set; }
#endif
            /// <summary>The well known Guid for the new tenant. If provided, this will be used to create the child tenant Id.</summary>
            [QueryParameter("wellKnownChildTenantGuid")]
            public Guid? WellKnownChildTenantGuid { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChildrenRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Marain.Tenancy.Client.Internal.Item.Marain.Tenant.Children.ChildrenRequestBuilder.ChildrenRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
