// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marain.Tenancy.Client.Internal.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Marain.Tenancy.Client.Internal.Models.Resource"/>, <see cref="global::Marain.Tenancy.Client.Internal.Models.TenantMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Tenant : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Marain.Tenancy.Client.Internal.Models.Resource"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Internal.Models.Resource? Resource { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Internal.Models.Resource Resource { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Marain.Tenancy.Client.Internal.Models.TenantMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Internal.Models.TenantMember1? TenantMember1 { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Internal.Models.TenantMember1 TenantMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Internal.Models.Tenant"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marain.Tenancy.Client.Internal.Models.Tenant CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Marain.Tenancy.Client.Internal.Models.Tenant();
            result.Resource = new global::Marain.Tenancy.Client.Internal.Models.Resource();
            result.TenantMember1 = new global::Marain.Tenancy.Client.Internal.Models.TenantMember1();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(Resource != null || TenantMember1 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(Resource, TenantMember1);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Internal.Models.Resource>(null, Resource, TenantMember1);
        }
    }
}
#pragma warning restore CS0618
