// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Marain.Tenancy.Client.Internal.Models
{
    /// <summary>The operation to be performed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateTenantJsonPatchEntry_op
    {
        [EnumMember(Value = "add")]
        #pragma warning disable CS1591
        Add,
        #pragma warning restore CS1591
        [EnumMember(Value = "replace")]
        #pragma warning disable CS1591
        Replace,
        #pragma warning restore CS1591
        [EnumMember(Value = "remove")]
        #pragma warning disable CS1591
        Remove,
        #pragma warning restore CS1591
    }
}
