// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Marain.Tenancy.Client.Internal.Models
{
    /// <summary>
    /// An operation describing one change to a tenant as part of an UpdateTenantJsonPatchArray
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateTenantJsonPatchEntry : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The operation to be performed.</summary>
        public global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_op? Op { get; set; }
        /// <summary>A JSON-Pointer. Either /name or /properties/propertyName</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The value to add or set</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry.UpdateTenantJsonPatchEntry_value? Value { get; set; }
#nullable restore
#else
        public global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry.UpdateTenantJsonPatchEntry_value Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry"/> and sets the default values.
        /// </summary>
        public UpdateTenantJsonPatchEntry()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "op", n => { Op = n.GetEnumValue<global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_op>(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "value", n => { Value = n.GetObjectValue<global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry.UpdateTenantJsonPatchEntry_value>(global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry.UpdateTenantJsonPatchEntry_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_op>("op", Op);
            writer.WriteStringValue("path", Path);
            writer.WriteObjectValue<global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry.UpdateTenantJsonPatchEntry_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="double"/>, <see cref="global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember1"/>, <see cref="global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember2"/>, <see cref="int"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateTenantJsonPatchEntry_value : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember1? UpdateTenantJsonPatchEntryValueMember1 { get; set; }
#nullable restore
#else
            public global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember1 UpdateTenantJsonPatchEntryValueMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember2? UpdateTenantJsonPatchEntryValueMember2 { get; set; }
#nullable restore
#else
            public global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember2 UpdateTenantJsonPatchEntryValueMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry.UpdateTenantJsonPatchEntry_value"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry.UpdateTenantJsonPatchEntry_value CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry.UpdateTenantJsonPatchEntry_value();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.UpdateTenantJsonPatchEntryValueMember1 = new global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember1();
                    result.UpdateTenantJsonPatchEntryValueMember2 = new global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UpdateTenantJsonPatchEntryValueMember1 != null || UpdateTenantJsonPatchEntryValueMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UpdateTenantJsonPatchEntryValueMember1, UpdateTenantJsonPatchEntryValueMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Marain.Tenancy.Client.Internal.Models.UpdateTenantJsonPatchEntry_valueMember1>(null, UpdateTenantJsonPatchEntryValueMember1, UpdateTenantJsonPatchEntryValueMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
